### ISSUE TITLE
something missing

### ISSUE THREAD

**Issue by vinnitu** [teacurran/wirelust-opencv-face-position#1]
error: could not convert ‘{{0, 0, 255}}’ from ‘<brace-enclosed initializer list>’ to ‘CvScalar’

**Comment by teacurran** [comment]
Sorry. I just saw this now. check the 'glitch' branch. that line had to change for the newer versions of OpenCV.

They basically changed:
`{{0,0,255}},`

so that it has to be:
`{0,0,255,0},`
